package com.eternal.main;

/* renamed from: com.eternal.main.BR */
public class C2323BR {
    public static final int CModel = 1;
    public static final int Item = 2;
    public static final int _all = 0;
    public static final int accountModel = 3;
    public static final int addWifiModel = 4;
    public static final int autoModel = 5;
    public static final int autoModelV4 = 6;
    public static final int changeModel = 7;
    public static final int childV4 = 8;
    public static final int chooseModel = 9;
    public static final int createModel = 10;
    public static final int existModel = 11;
    public static final int feedbackModel = 12;
    public static final int firmwareUpdateModel = 13;
    public static final int guideModel = 14;
    public static final int helpModel = 15;
    public static final int inviteModel = 16;
    public static final int item = 17;
    public static final int itemInvite = 18;
    public static final int itemPhoto = 19;
    public static final int itemSearch = 20;
    public static final int itemShare = 21;
    public static final int itemTimeZone = 22;
    public static final int itemV4 = 23;
    public static final int legalModel = 24;
    public static final int loginModel = 25;
    public static final int model = 26;
    public static final int modelV4 = 27;
    public static final int modelc = 28;
    public static final int open = 29;
    public static final int otherModel = 30;
    public static final int otherModelV4 = 31;
    public static final int permissionModel = 32;
    public static final int port = 33;
    public static final int preferenceModel = 34;
    public static final int promptModel = 35;
    public static final int resetModel = 36;
    public static final int searchModel = 37;
    public static final int shareModel = 38;
    public static final int supportModel = 39;
    public static final int targetModel = 40;
    public static final int technicalGuides = 41;
    public static final int timeZoneModel = 42;
    public static final int verifyModel = 43;
    public static final int versionModel = 44;
    public static final int wifiConnectModel = 45;
    public static final int wifiListModel = 46;
    public static final int wifiModel = 47;
    public static final int wifiSettingModel = 48;
}
