package com.eternal.base.database.entity;

import com.eternal.base.concat.PortInfo;
import java.util.ArrayList;
import java.util.List;

public class Device {
    public byte autoHighHum;
    public boolean autoHighHumSwitch;
    public byte autoHighTmp;
    public boolean autoHighTmpSwitch;
    public byte autoLowHum;
    public boolean autoLowHumSwitch;
    public byte autoLowTmp;
    public boolean autoLowTmpSwitch;
    public byte brightness;
    public byte bufferHum;
    public byte bufferTemp;
    public byte bufferTempC;
    public byte bufferVpd;
    public byte calibrationHumidity;
    public byte calibrationTemperature;
    public byte choosePort;
    public long connectTime;
    public byte connectType;
    public boolean currentTypeResidueOn;
    public int currentTypeResidueTime;
    public char cycleOff;
    public char cycleOn;
    public String deviceId;
    public int fan;
    public byte fanState;
    public byte fanType;
    public String firmwareVersion;
    public String hardwareVersion;
    public int highVpd;
    public boolean highVpdSwitch;
    public long historyTime;
    public int hum;
    public byte humState;
    public boolean isAdv;
    public boolean isControlTypeByHum;
    public boolean isDegree;
    public boolean isPlug;
    public byte isShare;
    public byte leafTemperatureC;
    public byte leafTemperatureF;
    public long logTime;
    public int lowVpd;
    public boolean lowVpdSwitch;
    public String mac;
    public String name;
    public byte port;
    public List<PortInfo> portList;
    public int portType;
    public byte schedOff;
    public byte schedOn;
    public boolean sequence;
    public String shareEmail;
    public String softwareVersion;
    public int targetHum = -32768;
    public int targetTmpC = -32768;
    public int targetTmpF = -32768;
    public int targetVpd = -32768;
    public char timeOff;
    public char timeOn;
    public int tmp;
    public byte tmpState;
    public byte transitionHumidity;
    public byte transitionTemperature;
    public byte transitionTemperatureC;
    public byte transitionVpd;
    public long triggerNotifyTime;
    public byte type;
    public String typeName;
    public byte typeOff;
    public byte typeOn;
    public byte version;
    public int vpd;
    public byte vpdState;
    public byte workType;

    public Device(String str) {
        this.mac = str;
    }

    public void init() {
        this.connectTime = System.currentTimeMillis();
        this.brightness = 5;
        this.calibrationTemperature = 4;
        this.calibrationHumidity = 4;
        this.transitionTemperature = 0;
        this.transitionHumidity = 0;
        this.typeOff = 0;
        this.typeOn = 6;
        this.workType = 1;
        this.timeOn = 0;
        this.timeOff = 0;
        this.autoHighTmp = 32;
        this.autoLowTmp = 32;
        this.autoHighHum = 0;
        this.autoLowHum = 0;
        this.cycleOn = 0;
        this.cycleOff = 0;
        this.schedOn = 0;
        this.schedOff = 0;
        this.autoHighHumSwitch = false;
        this.autoLowHumSwitch = false;
        this.autoHighTmpSwitch = false;
        this.autoLowTmpSwitch = false;
        this.portList = new ArrayList();
        this.fanType = 0;
        this.port = 0;
        this.leafTemperatureC = 0;
        this.leafTemperatureF = 0;
        this.targetTmpC = -32768;
        this.targetTmpF = -32768;
        this.targetHum = -32768;
        this.targetVpd = -32768;
    }
}
